# Generated by Django 5.1.6 on 2026-06-30 23:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antecedencia', models.IntegerField(default=30, help_text='Enviar alerta X dias antes da expiração', verbose_name='Dias de Antecedência')),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Canal de Envio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Configuração de Alerta',
                'verbose_name_plural': 'Configurações de Alerta',
                'db_table': 'configuracao_alerta',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail Gmail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone (+258)')),
                ('tipo_utilizador', models.CharField(choices=[('pescador', 'Pescador'), ('intransmar', 'INTRANSMAR'), ('admin', 'Administrador')], default='pescador', max_length=20, verbose_name='Tipo de Utilizador')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Nº Documento (BI/NUIT)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'db_table': 'utilizador',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Embarcacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Embarcação')),
                ('numero_matricula', models.CharField(max_length=50, unique=True, verbose_name='Nº Matrícula')),
                ('tipo_embarcacao', models.CharField(choices=[('canoa', 'Canoa'), ('canoa_motor', 'Canoa a Motor'), ('lancha', 'Lancha')], max_length=20, verbose_name='Tipo de Embarcação')),
                ('comprimento', models.FloatField(help_text='Máximo 10 metros para pesca artesanal', verbose_name='Comprimento (m)')),
                ('potencia_motor', models.IntegerField(default=0, help_text='Máximo 100 CV. Coloque 0 se não tiver motor.', verbose_name='Potência do Motor (CV)')),
                ('ano_construcao', models.IntegerField(verbose_name='Ano de Construção')),
                ('material', models.CharField(choices=[('madeira', 'Madeira'), ('fibra', 'Fibra de Vidro'), ('aluminio', 'Alumínio')], default='madeira', max_length=20, verbose_name='Material')),
                ('estado_registo', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Estado do Registo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('pescadores', models.ManyToManyField(blank=True, related_name='embarcacoes_pesca', to=settings.AUTH_USER_MODEL, verbose_name='Pescadores Associados')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarcacoes_proprias', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Embarcação',
                'verbose_name_plural': 'Embarcações',
                'db_table': 'embarcacao',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('licenca_pronta', 'Licença Pronta'), ('titulo_pronto', 'Título Pronto'), ('licenca_expirando', 'Licença a Expirar'), ('vistoria_expirando', 'Vistoria a Expirar'), ('relatorio', 'Relatório Gerado')], max_length=30, verbose_name='Tipo de Alerta')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('ambos', 'Ambos')], default='ambos', max_length=10, verbose_name='Canal')),
                ('numero_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Destino')),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('pendente', 'Pendente'), ('falhou', 'Falhou')], default='pendente', max_length=10, verbose_name='Estado')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('embarcacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.embarcacao', verbose_name='Embarcação')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LicencaNavegacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licenca', models.CharField(max_length=50, unique=True, verbose_name='Nº Licença')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de Referência')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.embarcacao', verbose_name='Embarcação')),
                ('emitida_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por')),
            ],
            options={
                'verbose_name': 'Licença de Navegação',
                'verbose_name_plural': 'Licenças de Navegação',
                'db_table': 'licenca_navegacao',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_manutencao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Manutenção')),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (MZN)')),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'Preventiva'), ('correctiva', 'Correctiva')], default='preventiva', max_length=20, verbose_name='Tipo de Manutenção')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.embarcacao', verbose_name='Embarcação')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'db_table': 'manutencao',
                'ordering': ['-data_manutencao'],
            },
        ),
        migrations.CreateModel(
            name='TituloPropriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titulo', models.CharField(max_length=50, unique=True, verbose_name='Nº Título')),
                ('data_emissao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('embarcacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titulo', to='core.embarcacao', verbose_name='Embarcação')),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por')),
            ],
            options={
                'verbose_name': 'Título de Propriedade',
                'verbose_name_plural': 'Títulos de Propriedade',
                'db_table': 'titulo_propriedade',
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vistoria', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Vistoria')),
                ('proxima_vistoria', models.DateField(blank=True, null=True, verbose_name='Próxima Vistoria')),
                ('resultado', models.CharField(choices=[('aprovada', 'Aprovada'), ('reprovada', 'Reprovada')], max_length=20, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('embarcacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='core.embarcacao', verbose_name='Embarcação')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Inspector')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'db_table': 'vistoria',
                'ordering': ['-data_vistoria'],
            },
        ),
    ]
