# Generated by Django 6.0.6 on 2026-07-02 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_gerados', to='core.configuracaoalerta', verbose_name='Configuração de Alerta'),
        ),
        migrations.AddField(
            model_name='configuracaoalerta',
            name='tipo_documento',
            field=models.CharField(choices=[('licenca', 'Licença de Navegação'), ('vistoria', 'Vistoria')], default='licenca', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='configuracaoalerta',
            name='utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_alerta', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
    ]
