# Generated by Django 6.0.6 on 2026-08-14 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alerta_configuracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulopropriedade',
            name='data_validade',
            field=models.DateField(blank=True, db_column='data_validade', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='configuracao',
            field=models.ForeignKey(blank=True, db_column='id_configuracao_alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_gerados', to='core.configuracaoalerta', verbose_name='Configuração de Alerta'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='destinatario',
            field=models.ForeignKey(db_column='id_utilizador', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='embarcacao',
            field=models.ForeignKey(blank=True, db_column='id_embarcacao', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='id',
            field=models.AutoField(db_column='id_alerta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuracaoalerta',
            name='id',
            field=models.AutoField(db_column='id_configuracao_alerta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='configuracaoalerta',
            name='utilizador',
            field=models.ForeignKey(blank=True, db_column='id_utilizador', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_alerta', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador'),
        ),
        migrations.AlterField(
            model_name='embarcacao',
            name='id',
            field=models.AutoField(db_column='id_embarcacao', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='embarcacao',
            name='proprietario',
            field=models.ForeignKey(db_column='id_utilizador', on_delete=django.db.models.deletion.CASCADE, related_name='embarcacoes_proprias', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='licencanavegacao',
            name='embarcacao',
            field=models.ForeignKey(db_column='id_embarcacao', on_delete=django.db.models.deletion.CASCADE, related_name='licencas', to='core.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='licencanavegacao',
            name='emitida_por',
            field=models.ForeignKey(db_column='id_utilizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencas_emitidas', to=settings.AUTH_USER_MODEL, verbose_name='Emitida por'),
        ),
        migrations.AlterField(
            model_name='licencanavegacao',
            name='id',
            field=models.AutoField(db_column='id_licenca_navegacao', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='embarcacao',
            field=models.ForeignKey(db_column='id_embarcacao', on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='core.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='id',
            field=models.AutoField(db_column='id_manutencao', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titulopropriedade',
            name='embarcacao',
            field=models.OneToOneField(db_column='id_embarcacao', on_delete=django.db.models.deletion.CASCADE, related_name='titulo', to='core.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='titulopropriedade',
            name='emitido_por',
            field=models.ForeignKey(db_column='id_utilizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Emitido por'),
        ),
        migrations.AlterField(
            model_name='titulopropriedade',
            name='id',
            field=models.AutoField(db_column='id_titulo_propriedade', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='id',
            field=models.AutoField(db_column='id_utilizador', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='embarcacao',
            field=models.ForeignKey(db_column='id_embarcacao', on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='core.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='id',
            field=models.AutoField(db_column='id_vistoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='inspector',
            field=models.ForeignKey(db_column='id_utilizador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='vistoria',
            name='proxima_vistoria',
            field=models.DateField(blank=True, db_column='data_proxima_vistoria', null=True, verbose_name='Próxima Vistoria'),
        ),
    ]
